export const ADD_TODO = "ADD_TODO";
export const REVERT_COMPLETE_TODO = "REVERT_COMPLETE_TODO";
export const REMOVE_TODO = "REMOVE_TODO";
export const CLEAR_COMPLETED = "CLEAR_COMPLETED";
export const FILTER_CHANGED = "FILTER_CHANGED";

export const FILTER_ALL = "ALL";
export const FILTER_ACTIVE = "ACTIVE";
export const FILTER_COMPLITED = "COMPLITED";